# -*- coding: utf-8 -*-
"""problem_116A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvXP_rA8hNpsvlDevxQF3YlyCtdBwdae
"""

n=int(input())
r,c=0,0
for i in range(n):
 a,b=map(int,input().split())
 c+=b-a
 r=max(r,c)
print(r)