# -*- coding: utf-8 -*-
"""problem_41A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10cu3LRghUbmyKP2YdeACZDAour4vPRxD
"""

s=str(input())
t=str(input())
count=0
if len(s)==len(t):
 for i in range(len(s)):
   if s[i]==t[-i+(-1)]:
    count+=1
   else:
    pass
 if count==len(s):
  print('YES')
 else:
  print('NO')
else:
  print('NO')