# -*- coding: utf-8 -*-
"""problem_344A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t-CENnxpDQ4mZZcxkm3LTWqmlGodtOZD
"""

x = int(input())
a = []
Count = 1

for i in range(x):
    n = input()
    a.append(n)

for i in range(x-1):
    if(a[i][-1]!=a[i+1][0]):
        continue
    else:
        Count = Count+1

print(Count)