# -*- coding: utf-8 -*-
"""problem_61A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8pC983rgB8lGnOH8icDmaeEnBIJ5xsU
"""

n=(input())
m=(input())
answer=''
for i in range(len(n)):
  if n[i]==m[i]:
    answer+='0'
  else:
    answer+='1'
print(answer)