# -*- coding: utf-8 -*-
"""problem_236A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvXP_rA8hNpsvlDevxQF3YlyCtdBwdae
"""

x=input()
a=[]
for i in range(len(x)):
  a.append(x[i])
if len(set(a)) %2!=0:
  print('IGNORE HIM!')
else:
  print('CHAT WITH HER!')