# -*- coding: utf-8 -*-
"""problem_263A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PWxv9RXjqecL49eF-s4E-T0k6W1afQB
"""

a = []

for i in range(5):
    b = list(map(int, input().split()))
    a.append(b)

for i in range(5):
    for j in range(5):
        if a[i][j] == 1:
            s = abs(i-2) + abs(j-2)
            print(s)
            break