# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

n = int(input())
s = input()
count = 0
for i in range(n-1):
    if s[i] == s[i+1]:
        count+=1
print(count)