# -*- coding: utf-8 -*-
"""problem_977A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6F_rYY5SpzeykEhwUl0foVa1t8yZoEr
"""

x=str(input())
a=[]
a.extend(x.split(' '))
n=int(a[0])
k=int(a[1])
for i in range(k):
  if n%10!=0:
    n-=1
  else:
    n/=10
print(int(n))