# -*- coding: utf-8 -*-
"""problem_469A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wZDvrJe-OnsshAige_eMCajPcw6GTsjv
"""

'''
=================   ==============   \          /   ==============|    =================    ||                   ||==============||   ||==============||       /||
||                  |            |    \        /   /                   ||             ||    ||                   ||              ||   ||              ||      / ||
||                  |            |     \      /   /                    ||             ||    ||                   ||              ||   ||              ||     /  ||
||                  |            |      \    /   /                     ||             ||    ||                   ||              ||   ||              ||    /   ||
||                  |            |       \  /   /                      ||             ||    ||                   ||              ||   ||              ||   /    ||
||========|         |            |        \/    =================      ||_____________||    ||                   ||              ||   ||              ||        ||
||                  |            |        ||                     /     ||             ||    ||                   ||              ||   ||              ||        ||
||                  |            |        ||                    /      ||             ||    ||                   ||              ||   ||              ||        ||
||                  |            |        ||                   /       ||             ||    ||                   ||              ||   ||              ||        ||
||                  ==============        ||    |=============/        ||             ||    ||===============||  ||==============||   ||==============||        ||


'''
n=int(input())
a=[int(i)for i in input().split()][1:]
b=[int(i)for i in input().split()][1:]
s=set(a+b)
if len(s)==n:
  print('I become the guy.')
else:
  print('Oh, my keyboard!')

