# -*- coding: utf-8 -*-
"""problem_110A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6F_rYY5SpzeykEhwUl0foVa1t8yZoEr
"""

x=str(input())
c=0
for i in range(len(x)):
  if int(x[i])==4 or int(x[i])==7 :
    c+=1
  else:
    pass
if c==4 or c==7:
  print('YES')
else:
  print('NO')