# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eO1rgI4r38XeWnx2pdILzWzQQx68mWm0
"""

n=int(input())
a=str(input())
b=[]
b.extend(a.split(' '))
count=0
for i in range(n):
  if int(b[i])>=1:
    count+=1
  else:
    pass
if count>0:
  print('HARD')
else:
  print('EASY')