# -*- coding: utf-8 -*-
"""problem_144A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hsV-PU8xT4G1LdfsMLpi7MGCM59tBVAE
"""

n=int(input())
a=list(map(int,input().split()))
min=a[0]
max=a[0]
minindex,maxindex=0,0
for i in range(1,n):
    if (a[i]>max):
        max=a[i]
        maxindex=i
    if (a[i]<=min):
        min=a[i]
        minindex=i

if minindex<maxindex:
    minindex=n-1-minindex
    print(maxindex+minindex-1)
else:
    minindex=n-1-minindex
    print(maxindex+minindex)