# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eO1rgI4r38XeWnx2pdILzWzQQx68mWm0
"""

u=int(input()[2:]);v=input()
while u:v=v.replace('BG','GB');u-=1
print(v)