# -*- coding: utf-8 -*-
"""problem_59Aipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1grPaJRPUia_HKl2HLKcaDE2VEBwSWm_m
"""

s=input()
a=len(s)
up_count=0
low_count=0
for i in range(a):
  if ord(s[i])>=65 and ord(s[i])<=90:
    up_count+=1
  else:
    low_count+=1
if up_count>low_count:
  print(s.upper())
else:
  print(s.lower())