# -*- coding: utf-8 -*-
"""problem_282A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZaWXaOFgyEz2yYTer3CKc-9peq6EkEAM
"""

#problem 282A
a=int(input())
x=0
for i in range(a):
  g=input()
  if '++' in g:
    x+=1
  else:
    x-=1

print(x)