# -*- coding: utf-8 -*-
"""problem_1328A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_gl3E8iOkwVt9NilhSV0uLm8fRaHyRgy
"""

t = int(input())
for i in range(t):
    l = input()
    a, b = [int(x) for x in l.split()]
    d = a % b
    if d == 0:
        print(0)
    else:
        print(b - d)