# -*- coding: utf-8 -*-
"""problem_136A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dkkCIJ8ee--6_xmeFszCJ16YG60OQVgY
"""

n = int(input())
mainList = list(map(int,input().split()))
AnsList = []

for i in range(n):
    AnsList.append(mainList.index(i+1)+1)

for i in AnsList:
    print(i,end=" ")