# -*- coding: utf-8 -*-
"""problem_271A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvXP_rA8hNpsvlDevxQF3YlyCtdBwdae
"""

y= int(input())
while y!=0:
    y+=1
    a=y%10
    b=(y//10)%10
    c=(y//100)%10
    d=(y//1000)%10
    if a!=b and a!=c and a!=d and b!=c and b!=d and c!=d:
        break
print(y)