# -*- coding: utf-8 -*-
"""problem_546A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xy_Or04Avw8U0n-LejPSpe-80dYWUjaB
"""

x=str(input())
a=[]
a.extend(x.split(' '))
k=int(a[0])
n=int(a[1])
w=int(a[2])
total=0
for i in range(w+1):
  k=int(a[0])
  k=k*i
  total+=k
if n>total:
  print('0')
else:
  print(total-n)