# -*- coding: utf-8 -*-
"""problem_200B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8pC983rgB8lGnOH8icDmaeEnBIJ5xsU
"""

n=int(input())
a=[]
x=input()
sum=0
a.extend(x.split(' '))
for i in range(len(a)):
  sum+=int(a[i])
orange=(sum/n)
print(orange)