# -*- coding: utf-8 -*-
"""Codeforces.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wuv_J4o6YpaY338AJiFe_fq8pQFADlp6
"""

x=int(input())
count=0
for i in range(x):
  a=list(input())

  if int(a[0])+int(a[2])+int(a[4]) >1:
    count+=1
  else:
    pass

print(count)