# -*- coding: utf-8 -*-
"""problem_50A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PWxv9RXjqecL49eF-s4E-T0k6W1afQB
"""

x=str(input())
a=[]
a.extend(x.split(' '))
area=(int(a[0]))*(int(a[1]))
sum=area//2
print(sum)