# -*- coding: utf-8 -*-
"""problem_228A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U8d2ovs62OqkgMRfF7jMlUFxbe-qhwvt
"""

n=input()
a=[]
count=0
a.extend(n.split(' '))
b=set(a)
count=4-len(b)
print(count)