# -*- coding: utf-8 -*-
"""problem_112A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvXP_rA8hNpsvlDevxQF3YlyCtdBwdae
"""

str1 = input().lower()
str2 = input().lower()
if str1 < str2:
    print("-1")
elif str1 > str2:
    print("1")
else:
    print("0")