# -*- coding: utf-8 -*-
"""problem_281A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zuU--m2GUmkb8egDeb_Xuj52Uz7EcFaa
"""

x=input()
if x[0].upper()==True:
  print(x)
else:
  a=x[0].upper()+x[1:]
  print(a)