# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

n=input()
a=[]
a.extend(n.split(' '))
limak=int(a[0])
bob=int(a[1])
count=0
while True:
  limak=limak*3
  bob=bob*2
  count+=1
  if limak>bob:
    break
  else:
    pass
print(count)