# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wuv_J4o6YpaY338AJiFe_fq8pQFADlp6
"""

distance=int(input())
count=0
if distance%5==0:
  print(int(distance/5))
else:
  a=distance%5
  b=distance-a
  count+=(b/5)
  if a%4==0:
    c=a/4
    count+=c
    print(int(count))
  elif a%3==0:
    d=a/3
    count+=d
    print(int(count))
  elif a%2==0:
    e=a/2
    count+=e
    print(int(count))
  else:
    count+=1
    print(int(count))