# -*- coding: utf-8 -*-
"""problem_734A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6F_rYY5SpzeykEhwUl0foVa1t8yZoEr
"""

x=int(input())
s=str(input())
a_count=0
d_count=0
for i in range(len(s)):
  if s[i]=='A':
    a_count+=1
  else:
    d_count+=1
if a_count>d_count:
  print('Anton')
elif d_count>a_count:
  print('Danik')
else:
  print('Friendship')