# -*- coding: utf-8 -*-
"""problem_467A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t-CENnxpDQ4mZZcxkm3LTWqmlGodtOZD
"""

x=int(input())
count=0
for i in range(x):
  n=str(input())
  a=[]
  a.extend(n.split(' '))
  if int(a[0])+2<=int(a[1]):
    count+=1
  else:
         pass
print(count)